env: prod
ocp_host: https://api.pipelines-prod.ijdb.p1.openshiftapps.com:6443
branch: main
operator_pipeline_webhook_secret: ../../vaults/prod/github-webhook-secret-prod.txt
kerberos_keytab: ../../vaults/prod/operatorpipelines.keytab

# how many of newest pipelineruns should be presrved on cleanup?
preserve_after_cleanup: 10
