---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ocp-environment-preparation
spec:
  params:
    - name: kubeconfig_dir
      description: Location of the kubeconfig for preflight-trigger
      default: /workspace/.kube
      type: string

    - name: ocp_version
      description: Version of OpenShift test cluster should be running.
      type: string

    - name: preflight_results_exists
      default: "false"
  results:
    - name: package_name
      description: Operator package name
    - name: bundle_version
      description: Operator bundle version
  steps:
    - name: clone-for-configs
      image: quay.io/redhat-isv/operator-pipelines-images:latest
      script: |
        #!/usr/bin/env bash
        echo "Cloning https://github.com/openshift/release to create ProwJob"
        git clone https://github.com/openshift/release
    
    - name: provision-cluster
      image: quay.io/opdev/preflight-trigger
      args:
        - '-job-config-path'
        - 'release/ci-operator/jobs/redhat-openshift-ecosystem/cvp/redhat-openshift-ecosystem-cvp-ocp-$(params.ocp_version)-periodics.yaml'
        - '-job-name'
        - 'periodic-ci-redhat-openshift-ecosystem-cvp-ocp-$(params.ocp_version)-cvp-common-aws'
        - '-ocp-version'
        - '$(params.ocp_version)'
        - '-prow-config-path'
        - 'release/core-services/prow/02_config/_config.yaml'
        - '-output-path'
        - '/workspace'
    
    - name: ls
      image: registry.access.redhat.com/ubi8/ubi-minimal
      script: |
        #!/usr/bin/env bash
        ls /workspace
        ls /workspace/.kube

